name: Python CI and Publishing

on:
  push:
    branches: [ "main", "feature/*", "fix/*", "refactor/*" ]
  pull_request:
    branches: [ "main", "feature/*", "fix/*", "refactor/*" ]
  release:
    types: [created]

permissions:
  contents: read

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Python and uv
        uses: astral-sh/setup-uv@4db96194c378173c656ce18a155ffc14a9fc4355 # v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: lint
        run: uv run task lint
      - name: Test with python ${{ matrix.python-version }}
        run: uv run --frozen task test


  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
      - test
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Install Python and uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
      - name: Build package
        run: uv build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.UV_PUBLISH_TOKEN }}