name: Renovate
on:
  workflow_dispatch:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
        RENOVATE_REPOSITORIES: mnboos/jsonschema-default,
#        RENOVATE_DRY_RUN: full
        RENOVATE_GIT_AUTHOR: Renovate Bot <mboos+renovatebot@outlook.com>
        RENOVATE_LOG_LEVEL: debug
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@02f4fdeb479bbb229caa7ad82cb5e691c07e80b3 # v41.0.14
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
